# git tag -d v1.2.0
# git push --delete origin v1.2.0
# git tag v1.2.0
# git push origin v1.2.0

permissions:
  contents: write
  
name: 'Build and release electron installer'
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and release on macOS
        if: runner.os == 'macOS'
        run: |
          npx electron-builder --mac --publish always
        env:
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and release on Windows
        if: runner.os == 'Windows'
        run: |
          npx electron-builder --win --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}